/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioCallModal: typeof import('./src/components/layouts/Modal/AudioCallModal.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseAvatar: typeof import('./src/components/common/BaseAvatar.vue')['default']
    BaseBadge: typeof import('./src/components/common/BaseBadge.vue')['default']
    Button: typeof import('primevue/button')['default']
    CallAlarmModal: typeof import('./src/components/layouts/Modal/CallAlarmModal.vue')['default']
    ChatInput: typeof import('./src/components/layouts/Window/ChatWindow/ChatInput.vue')['default']
    ChatList: typeof import('./src/components/layouts/AsideList/ChatList/ChatList.vue')['default']
    ChatListItem: typeof import('./src/components/layouts/AsideList/ChatList/ChatListItem.vue')['default']
    ChatWindow: typeof import('./src/components/layouts/Window/ChatWindow/ChatWindow.vue')['default']
    FileUpload: typeof import('./src/components/common/FileUpload.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FriendInfo: typeof import('./src/components/layouts/Window/FriendInfo.vue')['default']
    FriendList: typeof import('./src/components/layouts/AsideList/FriendList/FriendList.vue')['default']
    FriendListItem: typeof import('./src/components/layouts/AsideList/FriendList/FriendListItem.vue')['default']
    GroupAvatar: typeof import('./src/components/common/GroupAvatar.vue')['default']
    GroupInfo: typeof import('./src/components/layouts/Window/GroupInfo.vue')['default']
    GroupList: typeof import('./src/components/layouts/AsideList/GroupList/GroupList.vue')['default']
    GroupListItem: typeof import('./src/components/layouts/AsideList/GroupList/GroupListItem.vue')['default']
    ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MegaMenu: typeof import('primevue/megamenu')['default']
    Menu: typeof import('primevue/menu')['default']
    NaviBar: typeof import('./src/components/layouts/Navigator/NaviBar.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SettingWindow: typeof import('./src/components/layouts/Window/SettingWindow.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToolBar: typeof import('./src/components/layouts/Window/ChatWindow/ToolBar.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
    VideoCallModal: typeof import('./src/components/layouts/Modal/VideoCallModal.vue')['default']
  }
}

// For TSX support
declare global {
  const AudioCallModal: typeof import('./src/components/layouts/Modal/AudioCallModal.vue')['default']
  const Avatar: typeof import('primevue/avatar')['default']
  const Badge: typeof import('primevue/badge')['default']
  const BaseAvatar: typeof import('./src/components/common/BaseAvatar.vue')['default']
  const BaseBadge: typeof import('./src/components/common/BaseBadge.vue')['default']
  const Button: typeof import('primevue/button')['default']
  const CallAlarmModal: typeof import('./src/components/layouts/Modal/CallAlarmModal.vue')['default']
  const ChatInput: typeof import('./src/components/layouts/Window/ChatWindow/ChatInput.vue')['default']
  const ChatList: typeof import('./src/components/layouts/AsideList/ChatList/ChatList.vue')['default']
  const ChatListItem: typeof import('./src/components/layouts/AsideList/ChatList/ChatListItem.vue')['default']
  const ChatWindow: typeof import('./src/components/layouts/Window/ChatWindow/ChatWindow.vue')['default']
  const FileUpload: typeof import('./src/components/common/FileUpload.vue')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const Form: typeof import('@primevue/forms/form')['default']
  const FriendInfo: typeof import('./src/components/layouts/Window/FriendInfo.vue')['default']
  const FriendList: typeof import('./src/components/layouts/AsideList/FriendList/FriendList.vue')['default']
  const FriendListItem: typeof import('./src/components/layouts/AsideList/FriendList/FriendListItem.vue')['default']
  const GroupAvatar: typeof import('./src/components/common/GroupAvatar.vue')['default']
  const GroupInfo: typeof import('./src/components/layouts/Window/GroupInfo.vue')['default']
  const GroupList: typeof import('./src/components/layouts/AsideList/GroupList/GroupList.vue')['default']
  const GroupListItem: typeof import('./src/components/layouts/AsideList/GroupList/GroupListItem.vue')['default']
  const ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const MegaMenu: typeof import('primevue/megamenu')['default']
  const Menu: typeof import('primevue/menu')['default']
  const NaviBar: typeof import('./src/components/layouts/Navigator/NaviBar.vue')['default']
  const OverlayBadge: typeof import('primevue/overlaybadge')['default']
  const Panel: typeof import('primevue/panel')['default']
  const Password: typeof import('primevue/password')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('primevue/select')['default']
  const SettingWindow: typeof import('./src/components/layouts/Window/SettingWindow.vue')['default']
  const Toast: typeof import('primevue/toast')['default']
  const ToolBar: typeof import('./src/components/layouts/Window/ChatWindow/ToolBar.vue')['default']
  const UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
  const VideoCallModal: typeof import('./src/components/layouts/Modal/VideoCallModal.vue')['default']
}